// ─── Shared Bot Types (server + client) ─────────────────────────────────────

export type AIProvider = 'groq' | 'deepseek';

export interface BotConfig {
  groq: string;
  deepseek?: string;       // DeepSeek API key
  aiProvider?: AIProvider; // 'groq' (default) or 'deepseek'
  paper: boolean;
  key: string;
  secret: string;
  testnet: boolean;
  tgt: string;   // Telegram bot token
  tgc: string;   // Telegram chat ID
  sz: number;    // order size USDT
  mx: number;    // max open trades
  tp: number;    // take profit %
  sl: number;    // stop loss %
  lv: number;    // leverage
  mc: number;    // min confidence %
  trail?: boolean;     // trailing stop loss enabled (overrides fixed TP)
  trailDist?: number;  // trailing distance in % (e.g. 0.5 = SL trails 0.5% below peak)
  p: Record<string, { s?: boolean; f?: boolean }>;  // pairs by coin: { BTC: {s:true,f:true}, ETH: {...}, ... }
}

// Major coins available for trading (USDT pairs)
export const SUPPORTED_COINS = ['BTC', 'ETH', 'SOL', 'BNB', 'XRP', 'DOGE', 'ADA', 'AVAX', 'LINK', 'MATIC'] as const;
export type SupportedCoin = typeof SUPPORTED_COINS[number];

export interface OpenTrade {
  sym: string;
  mkt: string;
  cat: string;
  side: 'long' | 'short';
  entry: number;
  qty: number;
  tp: number;
  sl: number;
  time: number;
  conf: number;
  reasoning: string;
  key_factor: string;
  regime: string;
  paper?: boolean;
  peak?: number;       // highest favorable price seen (for trailing SL)
  trail?: boolean;     // snapshot: trailing was enabled at entry
  trailDist?: number;  // snapshot: trailing distance % at entry
}

export interface TradeLogEntry {
  time: string;
  sym: string;
  mkt: string;
  side: 'long' | 'short';
  entry: number;
  exit: number;
  pnl: string;
  reason: string;
  conf: number;
  reasoning: string;
}

export interface AIDecision {
  sym: string;
  mkt: string;
  thinking: boolean;
  action?: 'long' | 'short' | 'wait';
  confidence?: number;
  reasoning?: string;
  key_factor?: string;
  risk_level?: string;
  market_regime?: string;
  warnings?: string[];
  time?: string;
  price?: number;
}

export interface BotStats {
  pnl: number;
  trades: number;
  wins: number;
}

export type BotStatus = 'offline' | 'running' | 'thinking';

// ─── Strategy Memory & Learning ─────────────────────────────────────────────

/** A single strategy note — user instruction or AI-generated learning */
export interface StrategyNote {
  id: string;
  type: 'user' | 'learning';   // user = manual instruction, learning = AI-derived
  text: string;
  createdAt: string;            // ISO timestamp
  source?: string;              // e.g. "telegram", "app", "auto-analysis"
}

/** Trade performance insight generated by AI analysis of trade history */
export interface TradeLearning {
  pattern: string;              // e.g. "SHORT ETH in ranging market"
  outcome: 'winning' | 'losing';
  winRate: number;              // 0-100
  sampleSize: number;
  insight: string;              // AI-generated insight
  recommendation: string;       // what to do differently
  createdAt: string;
}

/** Full strategy state exposed to the client */
export interface StrategyState {
  notes: StrategyNote[];
  learnings: TradeLearning[];
  lastAnalysisTime: string | null;
  totalAnalyses: number;
}

// ─── Bot Snapshot ───────────────────────────────────────────────────────────

export interface BotSnapshot {
  config: Omit<BotConfig, 'groq' | 'key' | 'secret' | 'deepseek'>;
  status: BotStatus;
  paused: boolean;
  scanCount: number;
  nextScanIn: number;
  openTrades: Record<string, OpenTrade>;
  tradeLog: TradeLogEntry[];
  aiDecisions: Record<string, AIDecision>;
  stats: BotStats;
  newsHeadlines: string[];
  tickers: Record<string, { last: number; chg: number; vol: number } | null>;
  lastScanTime: string | null;
  strategy: StrategyState;
}

export const DEFAULT_CONFIG: BotConfig = {
  groq: '',
  deepseek: '',
  aiProvider: 'groq',
  paper: true,
  key: '',
  secret: '',
  testnet: false,
  tgt: '',
  tgc: '',
  sz: 20,
  mx: 2,
  tp: 0.5,
  sl: 0.25,
  lv: 5,
  mc: 65,
  trail: false,
  trailDist: 0.5,
  p: {
    BTC: { s: true, f: true },
    ETH: { s: true, f: true },
    SOL: { s: false, f: false },
    BNB: { s: false, f: false },
    XRP: { s: false, f: false },
    DOGE: { s: false, f: false },
    ADA: { s: false, f: false },
    AVAX: { s: false, f: false },
    LINK: { s: false, f: false },
    MATIC: { s: false, f: false },
  },
};
